### PR TITLE
fix: update pkg-config PREFIX replacing to work on @CMAKE_INSTALL_PREFIX@

### LINKED ISSUE #47: pkg-config string replacement needs to be updated
In `prefix=@CMAKE_INSTALL_PREFIX@`,  `@CMAKE_INSTALL_PREFIX@` needs to be replaced instead. Broken since https://github.com/extism/extism/pull/575

### PR DESCRIPTION
**Pull request by G4Vi**
Fixes #47

### CODE REVIEW

**Review by zshipko — APPROVED** [review]

File: lib.go [hunk 1]
```diff
@@ -256,7 +256,9 @@ func runLibInstall(cmd *cobra.Command, installArgs *libInstallArgs) error {
 							return err
 						}
 
-						if strings.HasPrefix(line, "prefix=PREFIX") {
+						if strings.HasPrefix(line, "prefix=") {
+							line = strings.ReplaceAll(line, "@CMAKE_INSTALL_PREFIX@",
+								installArgs.prefix)
 							line = strings.ReplaceAll(line, "PREFIX", installArgs.prefix)
```
Comment (zshipko) [inline lib.go:262]: This might be an issue if the CMAKE_INSTALL_PREFIX contains "PREFIX", which seems unlikely.

**Review by zshipko — APPROVED** [review]
